const {_electron}=require(process.env.PAPERDESK_BROWSER_MODULE||'playwright-core');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const data=fs.mkdtempSync(path.join(os.tmpdir(),'paperdesk-desktop-check-'));
const output=path.join(root,'build/test-results');fs.mkdirSync(output,{recursive:true});
const binary=process.env.PAPERDESK_TEST_EXECUTABLE;
const report={target:process.platform+'-'+process.arch,packaged:Boolean(binary),checks:[],errors:[],testData:data};
const components=process.env.PAPERDESK_TEST_COMPONENTS_DIR||path.join(root,'build/runtime',process.platform==='darwin'?'macos-arm64':'windows-x64','browsers');
const launch=()=>_electron.launch({...(binary?{executablePath:binary,args:[]}:{args:[root]}),env:{...process.env,PAPERDESK_TEST_DATA_DIR:data,PAPERDESK_TEST_COMPONENTS_DIR:components,PAPERDESK_TEST_OFFLINE:'1'},timeout:60000});
let app;
(async()=>{
 app=await launch();let page=await app.firstWindow();
 page.on('pageerror',e=>report.errors.push(e.message));
 await page.getByRole('heading',{name:'欢迎使用 Paperdesk'}).waitFor({timeout:30000});
 await page.screenshot({path:path.join(output,binary?'packaged-welcome.png':'welcome.png')});
 console.log((await page.locator('body').ariaSnapshot()).slice(-2300));
 await page.getByRole('textbox',{name:'我的姓名'}).fill('示例作者');
 await page.getByRole('textbox',{name:'其他署名'}).fill('Example Author');
 await page.getByRole('button',{name:'保存并开始'}).click();
 await page.getByRole('heading',{name:'添加期刊账号',exact:true}).waitFor();
 report.checks.push('First-run profile saved and account setup opened');
 console.log((await page.getByRole('dialog').ariaSnapshot()).slice(0,3500));
 await page.getByRole('textbox',{name:'期刊全名'}).fill('Desktop verification journal');
 await page.getByRole('textbox',{name:'简称'}).fill('TEST');
 await page.getByRole('textbox',{name:'登录网址'}).fill('https://example.test/journal');
 await page.getByRole('textbox',{name:'登录账号',exact:false}).fill('example@example.test');
 await page.getByRole('button',{name:/^保存(账号|稿件)$/}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:/投稿总览/}).click();
 await page.getByRole('button',{name:'添加稿件',exact:true}).click();
 console.log((await page.getByRole('dialog').ariaSnapshot()).slice(0,3500));
 await page.getByRole('combobox',{name:'投稿期刊'}).selectOption({label:'Desktop verification journal'});
 await page.getByRole('textbox',{name:'英文题目'}).fill('Example manuscript for desktop verification');
 await page.getByRole('combobox',{name:'第一作者'}).fill('Example Author');
 await page.getByRole('combobox',{name:'状态分类'}).selectOption('revision');
 await page.getByRole('button',{name:/^保存(账号|稿件)$/}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByText('Example manuscript for desktop verification',{exact:true}).first().waitFor();
 report.checks.push('Account and revision manuscript saved through visible UI');
 await page.getByRole('combobox',{name:'按作者身份筛选'}).selectOption('first');
 assert.equal(await page.locator('#paper-results').getByText('Example manuscript for desktop verification',{exact:true}).count(),1);
 report.checks.push('Configured English author alias recognized');
 await page.screenshot({path:path.join(output,binary?'packaged-overview.png':'overview.png')});
 await page.getByRole('button',{name:'个人与数据'}).click();
 const backupFile=path.join(data,'verification.paperdesk');
 await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},backupFile);
 await page.getByRole('button',{name:'导出备份',exact:true}).click();
 await page.getByRole('status').filter({hasText:'备份已保存'}).waitFor();
 assert.ok(fs.statSync(backupFile).size>0);
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});dialog.showMessageBox=async()=>({response:0});},backupFile);
 await page.getByRole('button',{name:'从备份恢复',exact:true}).click();
 await page.getByRole('status').filter({hasText:'稿件和设置已恢复'}).waitFor();
 report.checks.push('Native backup and restore actions complete against real database');
 await page.getByRole('button',{name:'取消',exact:true}).click();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());
 assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false);
 report.checks.push('Closing window retains background app');
 await app.close();app=null;
 app=await launch();page=await app.firstWindow();
 await page.getByText('Example manuscript for desktop verification',{exact:true}).first().waitFor({timeout:30000});
 assert.equal(await page.getByRole('heading',{name:'欢迎使用 Paperdesk'}).count(),0);
 report.checks.push('Relaunch preserves records and completed onboarding');
 await page.getByRole('button',{name:/期刊账号/}).click();
 await page.getByRole('button',{name:'编辑期刊',exact:true}).click();
 await page.getByRole('textbox',{name:'期刊全名'}).fill('Corrected verification journal');
 await page.getByRole('textbox',{name:'期刊简称'}).fill('EDIT');
 await page.getByRole('button',{name:'保存期刊',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('heading',{name:'Corrected verification journal',exact:true}).waitFor();
 await page.screenshot({path:path.join(output,binary?'packaged-journal-edit.png':'journal-edit.png')});
 await page.getByRole('button',{name:'添加该期刊的账号',exact:true}).click();
 await page.getByRole('textbox',{name:'登录账号',exact:false}).fill('remove@example.test');
 await page.getByRole('button',{name:'保存账号',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.locator('.journal-account').filter({hasText:'remove@example.test'}).getByRole('button',{name:'管理',exact:true}).click();
 await page.getByRole('button',{name:'删除账号',exact:true}).click();
 await page.getByRole('dialog').getByText(/1 个账号、0 篇稿件/).waitFor();
 await page.getByRole('button',{name:'取消',exact:true}).click();
 assert.equal(await page.locator('.journal-account').count(),2);
 await page.locator('.journal-account').filter({hasText:'remove@example.test'}).getByRole('button',{name:'管理',exact:true}).click();
 await page.getByRole('button',{name:'删除账号',exact:true}).click();
 await page.getByRole('button',{name:'确认删除',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.locator('.journal-account').filter({hasText:'remove@example.test'}).waitFor({state:'hidden'});
 assert.equal(await page.locator('.journal-account').count(),1);
 await page.getByRole('button',{name:'编辑期刊',exact:true}).click();
 await page.getByRole('button',{name:'删除期刊',exact:true}).click();
 await page.getByRole('dialog').getByText(/1 个账号、1 篇稿件/).waitFor();
 await page.screenshot({path:path.join(output,binary?'packaged-journal-delete.png':'journal-delete.png')});
 await page.getByRole('button',{name:'确认删除',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.locator('.journal-card').waitFor({state:'hidden'});
 assert.equal(await page.locator('.journal-card').count(),0);
 const deletedState=await page.evaluate(async()=> (await fetch('/api/state')).json());
 assert.deepEqual(deletedState.journals,[]);
 assert.deepEqual(deletedState.accounts,[]);
 assert.deepEqual(deletedState.manuscripts,[]);
 assert.deepEqual(deletedState.events,[]);
 report.checks.push('Journal rename, deletion cancellation, individual account deletion and journal cascade deletion work through visible UI');
 assert.deepEqual(report.errors,[]);
 await app.close();app=null;
 report.ok=true;
})().catch(error=>{report.ok=false;report.error=error.stack;console.error(error);process.exitCode=1;}).finally(async()=>{
 if(app)await app.close().catch(()=>{});
 fs.writeFileSync(path.join(output,binary?'packaged-smoke.json':'desktop-smoke.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
});
